# Generated by Django 4.0.4 on 2022-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0002_alter_contact_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
