# Generated by Django 4.0.4 on 2022-06-06 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0003_alter_contact_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 17, 26, 16, 285777)),
        ),
    ]
