# Generated by Django 4.0.4 on 2022-06-08 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0005_products_alter_contact_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 17, 0, 16, 634239)),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
