# Generated by Django 4.0.4 on 2022-06-08 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0006_alter_contact_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 17, 0, 20, 800867)),
        ),
    ]
