# Generated by Django 4.0.4 on 2022-06-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0007_alter_contact_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(),
        ),
    ]
