# Generated by Django 4.0.4 on 2022-06-10 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0008_alter_contact_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 15, 40, 27, 40065)),
        ),
    ]
