# Generated by Django 4.0.4 on 2022-06-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0010_alter_contact_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message_date',
        ),
    ]
