# Generated by Django 4.0.4 on 2022-06-12 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0011_remove_contact_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 12, 16, 27, 0, 668775)),
        ),
    ]
